from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from database_setup import Base, Country, Region, Craft, HandiCraft, Photo, Video, Myart, Artist

engine = create_engine('sqlite:///handmade.db')
# Bind the engine to the metadata of the Base class so that the
# declaratives can be accessed through a DBSession instance
Base.metadata.bind = engine

DBSession = sessionmaker(bind=engine)
# A DBSession() instance establishes all conversations with the database
# and represents a "staging zone" for all the objects loaded into the
# database session object. Any change made against the objects in the
# session won't be persisted into the database until you call
# session.commit(). If you're not happy about the changes, you can
# revert all of them back to the last commit by calling
# session.rollback()
session = DBSession()


country1 = Country(countryName = "Afghanistan")
session.add(country1)
session.commit()
country2 = Country(countryName = "Albania")
session.add(country2)
session.commit()
country3 = Country(countryName = "Algeria")
session.add(country3)
session.commit()
country4 = Country(countryName = "Algeria")
session.add(country4)
session.commit()
country5 = Country(countryName = "Algeria")
session.add(country5)
session.commit()
country6 = Country(countryName = "Algeria")
session.add(country6)
session.commit()
country7 = Country(countryName = "Algeria")
session.add(country7)
session.commit()
country8 = Country(countryName = "Australia")
session.add(country8)
session.commit()
country9 = Country(countryName = "Austria")
session.add(country9)
session.commit()
country10 = Country(countryName = "Azerbaijan")
session.add(country10)
session.commit()
country11 = Country(countryName = "Bahamas, The")
session.add(country11)
session.commit()
country12 = Country(countryName = "Bahrain")
session.add(country12)
session.commit()
country13 = Country(countryName = "Bangladesh")
session.add(country13)
session.commit()
country14 = Country(countryName = "Barbados")
session.add(country14)
session.commit()
country15 = Country(countryName = "Belarus")
session.add(country15)
session.commit()
country16 = Country(countryName = "Belgium")
session.add(country16)
session.commit()
country17 = Country(countryName = "Belize")
session.add(country17)
session.commit()
country18 = Country(countryName = "Benin")
session.add(country18)
session.commit()
country19 = Country(countryName = "Bhutan")
session.add(country19)
session.commit()
country20 = Country(countryName = "Bolivia")
session.add(country20)
session.commit()
country21 = Country(countryName = "Bosnia and Herzegovina")
session.add(country21)
session.commit()
country22 = Country(countryName = "Botswana")
session.add(country22)
session.commit()
country23 = Country(countryName = "Brazil")
session.add(country23)
session.commit()
country24 = Country(countryName = "Brunei")
session.add(country24)
session.commit()
country25 = Country(countryName = "Bulgaria")
session.add(country25)
session.commit()
country26 = Country(countryName = "Burkina Faso")
session.add(country26)
session.commit()
country27 = Country(countryName = "Burma")
session.add(country27)
session.commit()
country28 = Country(countryName = "Burundi")
session.add(country28)
session.commit()
country29 = Country(countryName = "Cambodia")
session.add(country29)
session.commit()
country30 = Country(countryName = "Cameroon")
session.add(country30)
session.commit()
country31 = Country(countryName = "Canada")
session.add(country31)
session.commit()
country32 = Country(countryName = "CaboVerde")
session.add(country32)
session.commit()
country33 = Country(countryName = "Central African Republic")
session.add(country33)
session.commit()
country34 = Country(countryName = "Chad")
session.add(country34)
session.commit()
country35 = Country(countryName = "Chile")
session.add(country35)
session.commit()
country36 = Country(countryName = "China")
session.add(country36)
session.commit()
country37 = Country(countryName = "Colombia")
session.add(country37)
session.commit()
country38 = Country(countryName = "Comoros")
session.add(country38)
session.commit()
country39 = Country(countryName = "Congo, Democratic Republic of the")
session.add(country39)
session.commit()
country40 = Country(countryName = "Congo, Republic of the")
session.add(country40)
session.commit()
country41 = Country(countryName = "Costa Rica")
session.add(country41)
session.commit()
country42 = Country(countryName = "Coted'Ivoire")
session.add(country42)
session.commit()
country43 = Country(countryName = "Croatia")
session.add(country43)
session.commit()
country44 = Country(countryName = "Cuba")
session.add(country44)
session.commit()
country45 = Country(countryName = "Curacao")
session.add(country45)
session.commit()
country46 = Country(countryName = "Cyprus")
session.add(country46)
session.commit()
country47 = Country(countryName = "Czechia")
session.add(country47)
session.commit()
country48 = Country(countryName = "Denmark")
session.add(country48)
session.commit()
country49 = Country(countryName = "Djibouti")
session.add(country49)
session.commit()
country50 = Country(countryName = "Dominica")
session.add(country50)
session.commit()
country51 = Country(countryName = "Dominican Republic")
session.add(country51)
session.commit()
country52 = Country(countryName = "East Timor(see Timor-Leste)")
session.add(country52)
session.commit()
country53 = Country(countryName = "Ecuador")
session.add(country53)
session.commit()
country54 = Country(countryName = "Egypt")
session.add(country54)
session.commit()
country55 = Country(countryName = "El Salvador")
session.add(country55)
session.commit()
country56 = Country(countryName = "Equatorial Guinea")
session.add(country56)
session.commit()
country57 = Country(countryName = "Eritrea")
session.add(country57)
session.commit()
country58 = Country(countryName = "Estonia")
session.add(country58)
session.commit()
country59 = Country(countryName = "Ethiopia")
session.add(country59)
session.commit()
country60 = Country(countryName = "Fiji")
session.add(country60)
session.commit()
country61 = Country(countryName = "Finland")
session.add(country61)
session.commit()
country62 = Country(countryName = "France")
session.add(country62)
session.commit()
country63 = Country(countryName = "Gabon")
session.add(country63)
session.commit()
country64 = Country(countryName = "Gambia, The")
session.add(country64)
session.commit()
country65 = Country(countryName = "Georgia")
session.add(country65)
session.commit()
country66 = Country(countryName = "Germany")
session.add(country66)
session.commit()
country67 = Country(countryName = "Ghana")
session.add(country67)
session.commit()
country68 = Country(countryName = "Greece")
session.add(country68)
session.commit()
country69 = Country(countryName = "Grenada")
session.add(country69)
session.commit()
country70 = Country(countryName = "Guatemala")
session.add(country70)
session.commit()
country71 = Country(countryName = "Guinea")
session.add(country71)
session.commit()
country72 = Country(countryName = "Guinea-Bissau")
session.add(country72)
session.commit()
country73 = Country(countryName = "Guyana")
session.add(country73)
session.commit()
country74 = Country(countryName = "Haiti")
session.add(country74)
session.commit()
country75 = Country(countryName = "HolySee")
session.add(country75)
session.commit()
country76 = Country(countryName = "Honduras")
session.add(country76)
session.commit()
country77 = Country(countryName = "Hong Kong")
session.add(country77)
session.commit()
country78 = Country(countryName = "Hungary")
session.add(country78)
session.commit()
country79 = Country(countryName = "Iceland")
session.add(country79)
session.commit()
country80 = Country(countryName = "India")
session.add(country80)
session.commit()
country81 = Country(countryName = "Indonesia")
session.add(country81)
session.commit()
country82 = Country(countryName = "Iran")
session.add(country82)
session.commit()
country83 = Country(countryName = "Iraq")
session.add(country83)
session.commit()
country84 = Country(countryName = "Ireland")
session.add(country84)
session.commit()
country85 = Country(countryName = "Israel")
session.add(country85)
session.commit()
country86 = Country(countryName = "Italy")
session.add(country86)
session.commit()
country87 = Country(countryName = "Jamaica")
session.add(country87)
session.commit()
country88 = Country(countryName = "Japan")
session.add(country88)
session.commit()
country89 = Country(countryName = "Jordan")
session.add(country89)
session.commit()
country90 = Country(countryName = "Kazakhstan")
session.add(country90)
session.commit()
country91 = Country(countryName = "Kenya")
session.add(country91)
session.commit()
country92 = Country(countryName = "Kiribati")
session.add(country92)
session.commit()
country93 = Country(countryName = "Korea, North")
session.add(country93)
session.commit()
country94 = Country(countryName = "Korea, South")
session.add(country94)
session.commit()
country95 = Country(countryName = "Kosovo")
session.add(country95)
session.commit()
country96 = Country(countryName = "Kuwait")
session.add(country96)
session.commit()
country97 = Country(countryName = "Kyrgyzstan")
session.add(country97)
session.commit()
country98 = Country(countryName = "Laos")
session.add(country98)
session.commit()
country99 = Country(countryName = "Latvia")
session.add(country99)
session.commit()
country100 = Country(countryName = "Lebanon")
session.add(country100)
session.commit()
country101 = Country(countryName = "Lesotho")
session.add(country101)
session.commit()
country102 = Country(countryName = "Liberia")
session.add(country102)
session.commit()
country103 = Country(countryName = "Libya")
session.add(country103)
session.commit()
country104 = Country(countryName = "Liechtenstein")
session.add(country104)
session.commit()
country105 = Country(countryName = "Lithuania")
session.add(country105)
session.commit()
country106 = Country(countryName = "Luxembourg")
session.add(country106)
session.commit()
country107 = Country(countryName = "Macau")
session.add(country107)
session.commit()
country108 = Country(countryName = "Macedonia")
session.add(country108)
session.commit()
country109 = Country(countryName = "Madagascar")
session.add(country109)
session.commit()
country110 = Country(countryName = "Malawi")
session.add(country110)
session.commit()
country111 = Country(countryName = "Malaysia")
session.add(country111)
session.commit()
country112 = Country(countryName = "Maldives")
session.add(country112)
session.commit()
country113 = Country(countryName = "Mali")
session.add(country113)
session.commit()
country114 = Country(countryName = "Malta")
session.add(country114)
session.commit()
country115 = Country(countryName = "MarshallIslands")
session.add(country115)
session.commit()
country116 = Country(countryName = "Mauritania")
session.add(country116)
session.commit()
country117 = Country(countryName = "Mauritius")
session.add(country117)
session.commit()
country118 = Country(countryName = "Mexico")
session.add(country118)
session.commit()
country119 = Country(countryName = "Micronesia")
session.add(country119)
session.commit()
country120 = Country(countryName = "Moldova")
session.add(country120)
session.commit()
country121 = Country(countryName = "Monaco")
session.add(country121)
session.commit()
country122 = Country(countryName = "Mongolia")
session.add(country122)
session.commit()
country123 = Country(countryName = "Montenegro")
session.add(country123)
session.commit()
country124 = Country(countryName = "Morocco")
session.add(country124)
session.commit()
country125 = Country(countryName = "Mozambique")
session.add(country125)
session.commit()
country126 = Country(countryName = "Namibia")
session.add(country126)
session.commit()
country127 = Country(countryName = "Nauru")
session.add(country127)
session.commit()
country128 = Country(countryName = "Nepal")
session.add(country128)
session.commit()
country129 = Country(countryName = "Netherlands")
session.add(country129)
session.commit()
country130 = Country(countryName = "NewZealand")
session.add(country130)
session.commit()
country131 = Country(countryName = "Nicaragua")
session.add(country131)
session.commit()
country132 = Country(countryName = "Niger")
session.add(country132)
session.commit()
country133 = Country(countryName = "Nigeria")
session.add(country133)
session.commit()
country134 = Country(countryName = "NorthKorea")
session.add(country134)
session.commit()
country135 = Country(countryName = "Norway")
session.add(country135)
session.commit()
country136 = Country(countryName = "Oman")
session.add(country136)
session.commit()
country137 = Country(countryName = "Pakistan")
session.add(country137)
session.commit()
country138 = Country(countryName = "Palau")
session.add(country138)
session.commit()
country139 = Country(countryName = "PalestinianTerritories")
session.add(country139)
session.commit()
country140 = Country(countryName = "Panama")
session.add(country140)
session.commit()
country141 = Country(countryName = "PapuaNewGuinea")
session.add(country141)
session.commit()
country142 = Country(countryName = "Paraguay")
session.add(country142)
session.commit()
country143 = Country(countryName = "Peru")
session.add(country143)
session.commit()
country144 = Country(countryName = "Philippines")
session.add(country144)
session.commit()
country145 = Country(countryName = "Poland")
session.add(country145)
session.commit()
country146 = Country(countryName = "Portugal")
session.add(country146)
session.commit()
country147 = Country(countryName = "Qatar")
session.add(country147)
session.commit()
country148 = Country(countryName = "Romania")
session.add(country148)
session.commit()
country149 = Country(countryName = "Russia")
session.add(country149)
session.commit()
country150 = Country(countryName = "Rwanda")
session.add(country150)
session.commit()
country151 = Country(countryName = "Saint Kitts and Nevis")
session.add(country151)
session.commit()
country152 = Country(countryName = "Saint Lucia")
session.add(country152)
session.commit()
country153 = Country(countryName = "Saint Vincent and the Grenadines")
session.add(country153)
session.commit()
country154 = Country(countryName = "Samoa")
session.add(country154)
session.commit()
country155 = Country(countryName = "San Marino")
session.add(country155)
session.commit()
country156 = Country(countryName = "Sao Tome and Principe")
session.add(country156)
session.commit()
country157 = Country(countryName = "Saudi Arabia")
session.add(country157)
session.commit()
country158 = Country(countryName = "Senegal")
session.add(country158)
session.commit()
country159 = Country(countryName = "Serbia")
session.add(country159)
session.commit()
country160 = Country(countryName = "Seychelles")
session.add(country160)
session.commit()
country161 = Country(countryName = "SierraLeone")
session.add(country161)
session.commit()
country162 = Country(countryName = "Singapore")
session.add(country162)
session.commit()
country163 = Country(countryName = "Sint Maarten")
session.add(country163)
session.commit()
country164 = Country(countryName = "Slovakia")
session.add(country164)
session.commit()
country165 = Country(countryName = "Slovenia")
session.add(country165)
session.commit()
country166 = Country(countryName = "Solomon Islands")
session.add(country166)
session.commit()
country167 = Country(countryName = "Somalia")
session.add(country167)
session.commit()
country168 = Country(countryName = "South Africa")
session.add(country168)
session.commit()
country169 = Country(countryName = "South Korea")
session.add(country169)
session.commit()
country170 = Country(countryName = "South Sudan")
session.add(country170)
session.commit()
country171 = Country(countryName = "Spain")
session.add(country171)
session.commit()
country172 = Country(countryName = "Sri Lanka")
session.add(country172)
session.commit()
country173 = Country(countryName = "Sudan")
session.add(country173)
session.commit()
country174 = Country(countryName = "Suriname")
session.add(country174)
session.commit()
country175 = Country(countryName = "Swaziland")
session.add(country175)
session.commit()
country176 = Country(countryName = "Sweden")
session.add(country176)
session.commit()
country177 = Country(countryName = "Switzerland")
session.add(country177)
session.commit()
country178 = Country(countryName = "Syria")
session.add(country178)
session.commit()
country179 = Country(countryName = "Taiwan")
session.add(country179)
session.commit()
country180 = Country(countryName = "Tajikistan")
session.add(country180)
session.commit()
country181 = Country(countryName = "Tanzania")
session.add(country181)
session.commit()
country182 = Country(countryName = "Thailand")
session.add(country182)
session.commit()
country183 = Country(countryName = "Timor-Leste")
session.add(country183)
session.commit()
country184 = Country(countryName = "Togo")
session.add(country184)
session.commit()
country185 = Country(countryName = "Tonga")
session.add(country185)
session.commit()
country186 = Country(countryName = "Trinidad and Tobago")
session.add(country186)
session.commit()
country187 = Country(countryName = "Tunisia")
session.add(country187)
session.commit()
country188 = Country(countryName = "Turkey")
session.add(country188)
session.commit()
country189 = Country(countryName = "Turkmenistan")
session.add(country189)
session.commit()
country190 = Country(countryName = "Tuvalu")
session.add(country190)
session.commit()
country191 = Country(countryName = "Uganda")
session.add(country191)
session.commit()
country192 = Country(countryName = "Ukraine")
session.add(country192)
session.commit()
country193 = Country(countryName = "United Arab Emirates")
session.add(country193)
session.commit()
country194 = Country(countryName = "United Kingdom")
session.add(country194)
session.commit()
country195 = Country(countryName = "Uruguay")
session.add(country195)
session.commit()
country196 = Country(countryName = "Uzbekistan")
session.add(country196)
session.commit()
country197 = Country(countryName = "Vanuatu")
session.add(country197)
session.commit()
country198 = Country(countryName = "Venezuela")
session.add(country198)
session.commit()
country199 = Country(countryName = "Vietnam")
session.add(country199)
session.commit()
country200 = Country(countryName = "Yemen")
session.add(country200)
session.commit()
country201 = Country(countryName = "Zambia")
session.add(country201)
session.commit()
country202 = Country(countryName = "Zimbabwe")
session.add(country202)
session.commit()
country203 = Country(countryName = "Other")
session.add(country203)
session.commit()

region1 = Region(cityName="Jaipur", country=country80)
session.add(region1)
session.commit()
region2 = Region(cityName="Other", country=country203)
session.add(region2)
session.commit()

craft1 = Craft(name = "Textile")
session.add(craft1)
session.commit()

craft2 = Craft(name = "Paper")
session.add(craft1)
session.commit()

craft3 = Craft(name = "Wood")
session.add(craft1)
session.commit()

craft4 = Craft(name = "Ceramic")
session.add(craft1)
session.commit()

craft5 = Craft(name = "Glass")
session.add(craft1)
session.commit()

craft6 = Craft(name = "Metal")
session.add(craft1)
session.commit()

craft7 = Craft(name = "Other")
session.add(craft1)
session.commit()


handiCraft1=HandiCraft(sub_craft="Banner-making", description="Something", region=region2, craft=craft1)
session.add(handiCraft1)
session.commit()

handiCraft2=HandiCraft(sub_craft="Canvas", description="Something", region=region2, craft=craft1)
session.add(handiCraft2)
session.commit()

handiCraft3=HandiCraft(sub_craft="work", description="Something", region=region2, craft=craft1)
session.add(handiCraft3)
session.commit()

handiCraft4=HandiCraft(sub_craft="Cross-stitch", description="Something", region=region2, craft=craft1)
session.add(handiCraft4)
session.commit()

handiCraft5=HandiCraft(sub_craft="Crocheting", description="Something", region=region2, craft=craft1)
session.add(handiCraft5)
session.commit()

handiCraft6=HandiCraft(sub_craft="Embroidery", description="Something", region=region2, craft=craft1)
session.add(handiCraft6)
session.commit()

handiCraft7=HandiCraft(sub_craft="Felting", description="Something", region=region2, craft=craft1)
session.add(handiCraft7)
session.commit()

handiCraft8=HandiCraft(sub_craft="Friendship", description="Something", region=region2, craft=craft1)
session.add(handiCraft8)
session.commit()

handiCraft9=HandiCraft(sub_craft="bracelet", description="Something", region=region2, craft=craft1)
session.add(handiCraft9)
session.commit()

handiCraft10=HandiCraft(sub_craft="Knitting", description="Something", region=region2, craft=craft1)
session.add(handiCraft10)
session.commit()

handiCraft11=HandiCraft(sub_craft="Lace-making", description="Something", region=region2, craft=craft1)
session.add(handiCraft11)
session.commit()

handiCraft12=HandiCraft(sub_craft="Lucet", description="Something", region=region2, craft=craft1)
session.add(handiCraft12)
session.commit()

handiCraft13=HandiCraft(sub_craft="Macrame", description="Something", region=region2, craft=craft1)
session.add(handiCraft13)
session.commit()

handiCraft14=HandiCraft(sub_craft="Millinery", description="Something", region=region2, craft=craft1)
session.add(handiCraft14)
session.commit()

handiCraft15=HandiCraft(sub_craft="Needlepoint", description="Something", region=region2, craft=craft1)
session.add(handiCraft15)
session.commit()

handiCraft16=HandiCraft(sub_craft="Needlework", description="Something", region=region2, craft=craft1)
session.add(handiCraft16)
session.commit()

handiCraft17=HandiCraft(sub_craft="Patchwork", description="Something", region=region2, craft=craft1)
session.add(handiCraft17)
session.commit()

handiCraft18=HandiCraft(sub_craft="Quilting", description="Something", region=region2, craft=craft1)
session.add(handiCraft18)
session.commit()

handiCraft19=HandiCraft(sub_craft="Ribbon embroidery", description="Something", region=region2, craft=craft1)
session.add(handiCraft19)
session.commit()

handiCraft20=HandiCraft(sub_craft="Rug hooking", description="Something", region=region2, craft=craft1)
session.add(handiCraft20)
session.commit()

handiCraft21=HandiCraft(sub_craft="Rug making", description="Something", region=region2, craft=craft1)
session.add(handiCraft21)
session.commit()

handiCraft22=HandiCraft(sub_craft="Sewing", description="Something", region=region2, craft=craft1)
session.add(handiCraft22)
session.commit()

handiCraft23=HandiCraft(sub_craft="Shoemaking", description="Something", region=region2, craft=craft1)
session.add(handiCraft23)
session.commit()

handiCraft24=HandiCraft(sub_craft="Spinning (textiles)", description="Something", region=region2, craft=craft1)
session.add(handiCraft24)
session.commit()

handiCraft25=HandiCraft(sub_craft="String art", description="Something", region=region2, craft=craft1)
session.add(handiCraft25)
session.commit()

handiCraft26=HandiCraft(sub_craft="Tapestry", description="Something", region=region2, craft=craft1)
session.add(handiCraft26)
session.commit()

handiCraft27=HandiCraft(sub_craft="Tatting", description="Something", region=region2, craft=craft1)
session.add(handiCraft27)
session.commit()

handiCraft28=HandiCraft(sub_craft="Tie-dye", description="Something", region=region2, craft=craft1)
session.add(handiCraft28)
session.commit()

handiCraft29=HandiCraft(sub_craft="Weaving", description="Something", region=region2, craft=craft1)
session.add(handiCraft29)
session.commit()

handiCraft30=HandiCraft(sub_craft="Altered book", description="Something", region=region2, craft=craft2)
session.add(handiCraft30)
session.commit()

handiCraft31=HandiCraft(sub_craft="Bookbinding", description="Something", region=region2, craft=craft2)
session.add(handiCraft31)
session.commit()

handiCraft32=HandiCraft(sub_craft="Calligraphy", description="Something", region=region2, craft=craft2)
session.add(handiCraft32)
session.commit()

handiCraft33=HandiCraft(sub_craft="Cardmaking", description="Something", region=region2, craft=craft2)
session.add(handiCraft33)
session.commit()

handiCraft34=HandiCraft(sub_craft="Cast paper", description="Something", region=region2, craft=craft2)
session.add(handiCraft34)
session.commit()

handiCraft35=HandiCraft(sub_craft="Collage", description="Something", region=region2, craft=craft2)
session.add(handiCraft35)
session.commit()

handiCraft36=HandiCraft(sub_craft="Decoupage", description="Something", region=region2, craft=craft2)
session.add(handiCraft36)
session.commit()

handiCraft37=HandiCraft(sub_craft="Photomontage", description="Something", region=region2, craft=craft2)
session.add(handiCraft37)
session.commit()

handiCraft38=HandiCraft(sub_craft="Embossing", description="Something", region=region2, craft=craft2)
session.add(handiCraft38)
session.commit()

handiCraft39=HandiCraft(sub_craft="Iris folding", description="Something", region=region2, craft=craft2)
session.add(handiCraft39)
session.commit()

handiCraft40=HandiCraft(sub_craft="Marbling", description="Something", region=region2, craft=craft2)
session.add(handiCraft40)
session.commit()

handiCraft41=HandiCraft(sub_craft="Origami( Kirigami + Moneygami)", description="Something", region=region2, craft=craft2)
session.add(handiCraft41)
session.commit()

handiCraft42=HandiCraft(sub_craft="Paper cutting", description="Something", region=region2, craft=craft2)
session.add(handiCraft42)
session.commit()

handiCraft43=HandiCraft(sub_craft="Paper toys", description="Something", region=region2, craft=craft2)
session.add(handiCraft43)
session.commit()

handiCraft44=HandiCraft(sub_craft="Papercraft", description="Something", region=region2, craft=craft2)
session.add(handiCraft44)
session.commit()

handiCraft45=HandiCraft(sub_craft="Papermaking", description="Something", region=region2, craft=craft2)
session.add(handiCraft45)
session.commit()

handiCraft46=HandiCraft(sub_craft="Papier-mache", description="Something", region=region2, craft=craft2)
session.add(handiCraft46)
session.commit()

handiCraft47=HandiCraft(sub_craft="Pop-up book", description="Something", region=region2, craft=craft2)
session.add(handiCraft47)
session.commit()

handiCraft48=HandiCraft(sub_craft="Quilling", description="Something", region=region2, craft=craft2)
session.add(handiCraft48)
session.commit()

handiCraft49=HandiCraft(sub_craft="Scrapbooking", description="Something", region=region2, craft=craft2)
session.add(handiCraft49)
session.commit()

handiCraft50=HandiCraft(sub_craft="Stamping", description="Something", region=region2, craft=craft2)
session.add(handiCraft50)
session.commit()

handiCraft51=HandiCraft(sub_craft="Wallpaper", description="Something", region=region2, craft=craft2)
session.add(handiCraft51)
session.commit()

handiCraft52=HandiCraft(sub_craft="Bentwood", description="Something", region=region2, craft=craft3)
session.add(handiCraft52)
session.commit()

handiCraft53=HandiCraft(sub_craft="Cabinetry", description="Something", region=region2, craft=craft3)
session.add(handiCraft53)
session.commit()

handiCraft54=HandiCraft(sub_craft="Carpentry", description="Something", region=region2, craft=craft3)
session.add(handiCraft54)
session.commit()

handiCraft55=HandiCraft(sub_craft="Chip carving", description="Something", region=region2, craft=craft3)
session.add(handiCraft55)
session.commit()

handiCraft56=HandiCraft(sub_craft="Ebeniste", description="Something", region=region2, craft=craft3)
session.add(handiCraft56)
session.commit()

handiCraft57=HandiCraft(sub_craft="Fretwork", description="Something", region=region2, craft=craft3)
session.add(handiCraft57)
session.commit()

handiCraft58=HandiCraft(sub_craft="Intarsia", description="Something", region=region2, craft=craft3)
session.add(handiCraft58)
session.commit()

handiCraft59=HandiCraft(sub_craft="Marquetry", description="Something", region=region2, craft=craft3)
session.add(handiCraft59)
session.commit()

handiCraft60=HandiCraft(sub_craft="Wood burning", description="Something", region=region2, craft=craft3)
session.add(handiCraft60)
session.commit()

handiCraft61=HandiCraft(sub_craft="Wood carving", description="Something", region=region2, craft=craft3)
session.add(handiCraft61)
session.commit()

handiCraft62=HandiCraft(sub_craft="Wood turning", description="Something", region=region2, craft=craft3)
session.add(handiCraft62)
session.commit()

handiCraft63=HandiCraft(sub_craft="Azulejo", description="Something", region=region2, craft=craft4)
session.add(handiCraft63)
session.commit()

handiCraft64=HandiCraft(sub_craft="Bone china", description="Something", region=region2, craft=craft4)
session.add(handiCraft64)
session.commit()

handiCraft65=HandiCraft(sub_craft="Earthenware", description="Something", region=region2, craft=craft4)
session.add(handiCraft65)
session.commit()

handiCraft66=HandiCraft(sub_craft="Porcelain", description="Something", region=region2, craft=craft4)
session.add(handiCraft66)
session.commit()

handiCraft67=HandiCraft(sub_craft="Pottery", description="Something", region=region2, craft=craft4)
session.add(handiCraft67)
session.commit()

handiCraft68=HandiCraft(sub_craft="Stoneware", description="Something", region=region2, craft=craft4)
session.add(handiCraft68)
session.commit()

handiCraft69=HandiCraft(sub_craft="Terracotta", description="Something", region=region2, craft=craft4)
session.add(handiCraft69)
session.commit()

handiCraft70=HandiCraft(sub_craft="Cameo glass", description="Something", region=region2, craft=craft5)
session.add(handiCraft70)
session.commit()

handiCraft71=HandiCraft(sub_craft="Glassware", description="Something", region=region2, craft=craft5)
session.add(handiCraft71)
session.commit()

handiCraft72=HandiCraft(sub_craft="Stained glass", description="Something", region=region2, craft=craft5)
session.add(handiCraft72)
session.commit()

handiCraft73=HandiCraft(sub_craft="Engraving", description="Something", region=region2, craft=craft6)
session.add(handiCraft73)
session.commit()

handiCraft74=HandiCraft(sub_craft="Jewellery", description="Something", region=region2, craft=craft6)
session.add(handiCraft74)
session.commit()

handiCraft75=HandiCraft(sub_craft="Goldsmith", description="Something", region=region2, craft=craft6)
session.add(handiCraft75)
session.commit()

handiCraft76=HandiCraft(sub_craft="Silversmith", description="Something", region=region2, craft=craft6)
session.add(handiCraft76)
session.commit()

handiCraft77=HandiCraft(sub_craft="Assemblage", description="Something", region=region2, craft=craft7)
session.add(handiCraft77)
session.commit()

handiCraft78=HandiCraft(sub_craft="Balloon modelling", description="Something", region=region2, craft=craft7)
session.add(handiCraft78)
session.commit()

handiCraft79=HandiCraft(sub_craft="Beadwork", description="Something", region=region2, craft=craft7)
session.add(handiCraft79)
session.commit()

handiCraft80=HandiCraft(sub_craft="Bone carving", description="Something", region=region2, craft=craft7)
session.add(handiCraft80)
session.commit()

handiCraft81=HandiCraft(sub_craft="Doll making", description="Something", region=region2, craft=craft7)
session.add(handiCraft81)
session.commit()

handiCraft82=HandiCraft(sub_craft="Dollhouse", description="Something", region=region2, craft=craft7)
session.add(handiCraft82)
session.commit()

handiCraft83=HandiCraft(sub_craft="Egg decorating", description="Something", region=region2, craft=craft7)
session.add(handiCraft83)
session.commit()

handiCraft84=HandiCraft(sub_craft="Engraved gems", description="Something", region=region2, craft=craft7)
session.add(handiCraft84)
session.commit()

handiCraft85=HandiCraft(sub_craft="Hardstone carving", description="Something", region=region2, craft=craft7)
session.add(handiCraft85)
session.commit()

handiCraft86=HandiCraft(sub_craft="Lathart", description="Something", region=region2, craft=craft7)
session.add(handiCraft86)
session.commit()

handiCraft87=HandiCraft(sub_craft="Lapidary", description="Something", region=region2, craft=craft7)
session.add(handiCraft87)
session.commit()

handiCraft88=HandiCraft(sub_craft="Leatherworking", description="Something", region=region2, craft=craft7)
session.add(handiCraft88)
session.commit()

handiCraft89=HandiCraft(sub_craft="Miniatures", description="Something", region=region2, craft=craft7)
session.add(handiCraft89)
session.commit()

handiCraft90=HandiCraft(sub_craft="Micromosaic", description="Something", region=region2, craft=craft7)
session.add(handiCraft90)
session.commit()

handiCraft91=HandiCraft(sub_craft="Mosaic", description="Something", region=region2, craft=craft7)
session.add(handiCraft91)
session.commit()

handiCraft92=HandiCraft(sub_craft="Pietra dura", description="Something", region=region2, craft=craft7)
session.add(handiCraft92)
session.commit()

handiCraft93=HandiCraft(sub_craft="Pressed flower craft", description="Something", region=region2, craft=craft7)
session.add(handiCraft93)
session.commit()

handiCraft94=HandiCraft(sub_craft="Scrimshaw", description="Something", region=region2, craft=craft7)
session.add(handiCraft94)
session.commit()

handiCraft95=HandiCraft(sub_craft="Straw marquetry", description="Something", region=region2, craft=craft7)
session.add(handiCraft95)
session.commit()

handiCraft96=HandiCraft(sub_craft="Wall decal", description="A wall decal, also known as a wall sticker, wall tattoo, or wall vinyl, is a vinyl sticker that is affixed to a wall or other smooth surface for decoration and informational purposes. Wall decals are cut with vinyl cutting machines. Most decals use only one color, but some may have various images printed upon them.", region=region2, craft=craft7)
session.add(handiCraft96)
session.commit()

artist1=Artist(name="Anuja Verma")
session.add(artist1)
session.commit()

photo1=Photo(photoURL="https://i.pinimg.com/736x/6c/4b/cb/6c4bcb707d06917954ff0a3f4fb5c177--mandala-wall-decal-mandala-decor.jpg", handicraft=handiCraft96)
session.add(photo1)
session.commit()

video1=Video(videoURL="https://www.youtube.com/watch?v=qvCRL2Z5_Ho", handicraft=handiCraft96)
session.add(video1)
session.commit()

myart1=Myart(title="Mandala Wall decalling", artist=artist1, handicraft=handiCraft96, photo=photo1, video=video1)
session.add(myart1)
session.commit()




print ("added menu items!")